import type { BusinessProfile, PricingRule, Slot, Turf } from "./types";

export const businessProfile: BusinessProfile = {
  name: "Turfy Sports Arena",
  tagline: "Book your next football match without calling the counter.",
  phone: "+880 1711-000000",
  email: "booking@turfy.example",
  address: "Road 12, Bashundhara R/A",
  city: "Dhaka",
  openingSummary: "Open daily from 6:00 AM to 12:00 AM",
};

export const turfs: Turf[] = [
  {
    id: "bashundhara-5v5",
    name: "Bashundhara 5v5 Turf",
    description:
      "Compact floodlit 5-a-side football turf suited for evening matches and quick team practice sessions.",
    area: "Bashundhara R/A",
    city: "Dhaka",
    address: "Block C, Road 12, Bashundhara R/A, Dhaka",
    size: "5v5",
    sports: ["Football"],
    facilities: ["Floodlights", "Parking", "Washroom", "Drinking water", "Seating"],
    openingTime: "06:00",
    closingTime: "24:00",
    defaultPrice: 2500,
    imageUrl:
      "https://images.unsplash.com/photo-1556056504-5c7696c4c28d?auto=format&fit=crop&w=1200&q=80",
    isPublished: true,
  },
  {
    id: "uttara-7v7",
    name: "Uttara 7v7 Arena",
    description:
      "Larger 7-a-side turf with extra seating and changing room support for regular club bookings.",
    area: "Uttara Sector 7",
    city: "Dhaka",
    address: "Sector 7, Uttara, Dhaka",
    size: "7v7",
    sports: ["Football"],
    facilities: [
      "Floodlights",
      "Parking",
      "Washroom",
      "Changing room",
      "Drinking water",
      "Seating",
    ],
    openingTime: "07:00",
    closingTime: "23:00",
    defaultPrice: 3800,
    imageUrl:
      "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=1200&q=80",
    isPublished: true,
  },
  {
    id: "mirpur-training",
    name: "Mirpur Training Ground",
    description:
      "Morning-friendly training turf with quieter slots and lower daytime pricing for academy sessions.",
    area: "Mirpur DOHS",
    city: "Dhaka",
    address: "Avenue 4, Mirpur DOHS, Dhaka",
    size: "6v6",
    sports: ["Football"],
    facilities: ["Floodlights", "Washroom", "Prayer space", "Drinking water"],
    openingTime: "06:00",
    closingTime: "22:00",
    defaultPrice: 3000,
    imageUrl:
      "https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=1200&q=80",
    isPublished: true,
  },
];

export const slots: Slot[] = [
  {
    id: "slot-bash-1800",
    turfId: "bashundhara-5v5",
    date: "2026-04-27",
    startTime: "18:00",
    endTime: "19:00",
    basePrice: 2500,
    finalPrice: 3200,
    status: "available",
  },
  {
    id: "slot-bash-1900",
    turfId: "bashundhara-5v5",
    date: "2026-04-27",
    startTime: "19:00",
    endTime: "20:00",
    basePrice: 2500,
    finalPrice: 3200,
    status: "booked",
  },
  {
    id: "slot-bash-2000",
    turfId: "bashundhara-5v5",
    date: "2026-04-27",
    startTime: "20:00",
    endTime: "21:00",
    basePrice: 2500,
    finalPrice: 3200,
    status: "pending_payment",
  },
  {
    id: "slot-bash-2100",
    turfId: "bashundhara-5v5",
    date: "2026-04-27",
    startTime: "21:00",
    endTime: "22:00",
    basePrice: 2500,
    finalPrice: 3200,
    status: "available",
  },
  {
    id: "slot-uttara-1700",
    turfId: "uttara-7v7",
    date: "2026-04-27",
    startTime: "17:00",
    endTime: "18:00",
    basePrice: 3800,
    finalPrice: 4200,
    status: "available",
  },
  {
    id: "slot-uttara-1800",
    turfId: "uttara-7v7",
    date: "2026-04-27",
    startTime: "18:00",
    endTime: "19:00",
    basePrice: 3800,
    finalPrice: 4500,
    status: "available",
  },
  {
    id: "slot-mirpur-0800",
    turfId: "mirpur-training",
    date: "2026-04-27",
    startTime: "08:00",
    endTime: "09:00",
    basePrice: 3000,
    finalPrice: 2200,
    status: "available",
  },
  {
    id: "slot-mirpur-0900",
    turfId: "mirpur-training",
    date: "2026-04-27",
    startTime: "09:00",
    endTime: "10:00",
    basePrice: 3000,
    finalPrice: 2200,
    status: "unavailable",
  },
];

export const pricingRules: PricingRule[] = [
  {
    id: "rule-evening-peak",
    turfId: "bashundhara-5v5",
    name: "Evening peak",
    type: "time_of_day",
    startTime: "18:00",
    endTime: "23:00",
    price: 3200,
    priority: 40,
    isActive: true,
  },
  {
    id: "rule-uttara-weekend",
    turfId: "uttara-7v7",
    name: "Weekend premium",
    type: "weekend",
    dayOfWeek: 5,
    price: 4500,
    priority: 50,
    isActive: true,
  },
  {
    id: "rule-mirpur-morning",
    turfId: "mirpur-training",
    name: "Morning training",
    type: "time_of_day",
    startTime: "06:00",
    endTime: "11:00",
    price: 2200,
    priority: 40,
    isActive: true,
  },
];
